DROP TABLE IF EXISTS RETAIL;
CREATE TABLE RETAIL (
	TRANSACTION_ID INT PRIMARY KEY,
	ORDER_DATE DATE,
	CUSTOMER_ID TEXT,
	MARITAL_STATUS VARCHAR(100),
	GENDER VARCHAR(10),
	AGE INT,
	PRODUCT_CATEGORY TEXT,
	QUANTITY INT,
	PRICE_PER_UNIT NUMERIC(10, 2),
	TOTAL_AMOUNT NUMERIC(10, 2),
	COUNTRY VARCHAR(100)
);

SELECT * FROM RETAIL
	
-- BACKUP TBALE
CREATE TABLE sales_backup AS TABLE Retail;

-- CLEANING TABLE
-- 1. Remove duplicates based on Transaction_ID
DELETE FROM RETAIL
WHERE CTID NOT IN(
     SELECT MIN(CTID)
	 FROM RETAIL
	 GROUP BY TRANSACTION_ID
);	 
-- 2. Remove rows with critical NULLs	 
SELECT * FROM RETAIL
WHERE
	TRANSACTION_ID IS NULL
	OR CUSTOMER_ID IS NULL
	OR PRODUCT_CATEGORY IS NULL
	OR QUANTITY IS NULL
	OR PRICE_PER_UNIT IS NULL;

-- 3. DELETING ROWS WHERE IDs ARE NULL AND IF NUMERIC OR CATEGORICAL ROW IS NULL THEN FILLING IT WITH MEAN OR MODE
DELETE FROM RETAIL
WHERE
	TRANSACTION_ID IS NULL
	OR CUSTOMER_ID IS NULL
UPDATE RETAIL
SET QUANTITY = ( SELECT AVG(QUANTITY) FROM RETAIL)
WHERE QUANTITY IS NULL;

UPDATE RETAIL
SET PRICE_PER_UNIT = ( SELECT AVG(PRICE_PER_UNIT) FROM RETAIL)
WHERE PRICE_PER_UNIT IS NULL;

UPDATE RETAIL
SET PRODUCT_CATEGORY = (SELECT PRODUCT_CATEGORY FROM RETAIL GROUP BY PRODUCT_CATEGORY ORDER BY COUNT(*) DESC LIMIT
			1)
WHERE PRODUCT_CATEGORY IS NULL;

-- 4. Standardize Gender
UPDATE RETAIL
SET GENDER = 'Male'
WHERE LOWER(GENDER) IN ('m', 'male');

UPDATE RETAIL
SET GENDER = 'Female'
WHERE LOWER(GENDER)IN ('f', 'female');

-- 5. Standardize Product Category (remove spaces and uppercase)
UPDATE RETAIL
SET PRODUCT_CATEGORY = UPPER(TRIM(PRODUCT_CATEGORY));

-- 6. Fix Total_Amount to match Quantity * Price_per_Unit
UPDATE RETAIL
SET TOTAL_AMOUNT = QUANTITY * PRICE_PER_UNIT
WHERE TOTAL_AMOUNT IS NULL
	OR TOTAL_AMOUNT <> QUANTITY * PRICE_PER_UNIT;



-- Consumer Behavior Analysis

-- Customer Demographic
SELECT
	GENDER,
	COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER FROM RETAIL
GROUP BY GENDER;
SELECT
	CASE
		WHEN AGE < 18 THEN 'Under 18'
		WHEN AGE BETWEEN 18 AND 25  THEN '18–25'
		WHEN AGE BETWEEN 26 AND 35  THEN '26–35'
		WHEN AGE BETWEEN 36 AND 50  THEN '36–50'
		ELSE '50+'
	END AS AGE_GROUP,
	COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMERS
FROM RETAIL
GROUP BY AGE_GROUP
ORDER BY CUSTOMERS DESC;

SELECT COUNTRY,TOTAL_AMOUNT  FROM RETAIL
ORDER BY TOTAL_AMOUNT DESC
LIMIT 5;

WITH UK AS 
   (SELECT COUNT(TRANSACTION_ID) AS FREQUENCY , COUNTRY  FROM RETAIL
   GROUP BY CUSTOMER_ID,COUNTRY
   ),COUNTRY AS 
   (SELECT COUNTRY , AVG(FREQUENCY) AS AVG_FREQ FROM UK
   GROUP BY COUNTRY )
SELECT * FROM COUNTRY
ORDER BY AVG_FREQ

SELECT MARITAL_STATUS , SUM(QUANTITY) AS SUM_QUANT FROM RETAIL
GROUP BY MARITAL_STATUS
ORDER BY SUM_QUANT

SELECT 
MARITAL_STATUS,
CASE WHEN TRANSACTION_COUNT = 1 THEN 'ONE-TIME'
ELSE 'REPEAT'
END AS CUSTOMER_TYPE, 
COUNT(*) AS CUSTOMER
FROM (SELECT COUNT(TRANSACTION_ID) AS TRANSACTION_COUNT, CUSTOMER_ID,MARITAL_STATUS FROM RETAIL
GROUP BY CUSTOMER_ID , MARITAL_STATUS)T
GROUP BY CUSTOMER_TYPE,MARITAL_STATUS
 

-- Purchase Frequency
SELECT CUSTOMER_ID,COUNT(TRANSACTION_ID) AS TOTAL_ORDERS
FROM RETAIL
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_ORDERS DESC;

SELECT -- One-time vs Repeat Customers
	CASE
		WHEN TRANSACTION_COUNT = 1 THEN 'One-time'
		ELSE 'Repeat'
	END AS CUSTOMER_TYPE,
	COUNT(*) AS CUSTOMERS
FROM(SELECT 
        CUSTOMER_ID,
	    COUNT(TRANSACTION_ID) AS TRANSACTION_COUNT
		FROM RETAIL
		GROUP BY CUSTOMER_ID
	) T
GROUP BY CUSTOMER_TYPE;

-- Spending Behavior
SELECT CUSTOMER_ID,
	   ROUND(AVG(TOTAL_AMOUNT), 2) AS AVG_SPEND
FROM RETAIL
GROUP BY CUSTOMER_ID
ORDER BY AVG_SPEND DESC;

WITH
	SPEND AS ( --High-Value Customers (Top 20%)
		SELECT CUSTOMER_ID,SUM(TOTAL_AMOUNT) AS TOTAL_SPENT FROM RETAIL
		GROUP BY CUSTOMER_ID
	)
SELECT * FROM SPEND
WHERE TOTAL_SPENT >= (SELECT PERCENTILE_CONT(0.8) WITHIN GROUP (ORDER BY TOTAL_SPENT)
		FROM SPEND
	);

-- Product Preferences
SELECT PRODUCT_CATEGORY,
SUM(QUANTITY) AS UNITS_SOLD
FROM RETAIL
GROUP BY PRODUCT_CATEGORY
ORDER BY UNITS_SOLD DESC;

SELECT GENDER, PRODUCT_CATEGORY,SUM(QUANTITY) AS UNITS_SOLD
FROM RETAIL
GROUP BY GENDER, PRODUCT_CATEGORY
ORDER BY GENDER,UNITS_SOLD DESC;

-- Time-Based Behavior
SELECT
	DATE_TRUNC('month', ORDER_DATE) AS MONTH,
	COUNT(TRANSACTION_ID) AS ORDERS,
	PRODUCT_CATEGORY
FROM RETAIL
GROUP BY MONTH,PRODUCT_CATEGORY
ORDER BY MONTH;

SELECT
	CASE
		WHEN EXTRACT(DOW FROM ORDER_DATE) IN (0, 6) THEN 'Weekend'
		ELSE 'Weekday'
	END AS DAY_TYPE,
	COUNT(TRANSACTION_ID) AS ORDERS
FROM RETAIL
GROUP BY DAY_TYPE;

-- RFM Analysis
SELECT
	CUSTOMER_ID,
	MAX(ORDER_DATE) AS LAST_PURCHASE_DATE,
	COUNT(TRANSACTION_ID) AS FREQUENCY,
	SUM(TOTAL_AMOUNT) AS MONETARY
FROM RETAIL
GROUP BY CUSTOMER_ID;

WITH RFM_BASE AS ( -- (Days Since Last Purchase)
	SELECT
		CUSTOMER_ID,
		MAX(ORDER_DATE) AS LAST_PURCHASE_DATE,
		COUNT(TRANSACTION_ID) AS FREQUENCY,
		SUM(TOTAL_AMOUNT) AS MONETARY
	FROM RETAIL
	GROUP BY CUSTOMER_ID
)
SELECT
	CUSTOMER_ID,
	DATE '2024-01-01' - LAST_PURCHASE_DATE AS RECENCY,
	FREQUENCY,
	MONETARY
FROM RFM_BASE;

-- Customer Lifecycle Behavior
WITH CUSTOMER_SUMMARY AS (
	SELECT
		CUSTOMER_ID,
		COUNT(TRANSACTION_ID) AS TOTAL_ORDERS,
		MAX(ORDER_DATE) AS LAST_PURCHASE
	FROM RETAIL
	GROUP BY CUSTOMER_ID
)
SELECT
	CUSTOMER_ID,
	TOTAL_ORDERS,
	LAST_PURCHASE,
	CASE
		WHEN TOTAL_ORDERS = 1 THEN 'New'
		WHEN LAST_PURCHASE >= CURRENT_DATE - INTERVAL '30 days' THEN 'Active'
		WHEN LAST_PURCHASE >= CURRENT_DATE - INTERVAL '90 days' THEN 'At Risk'
		ELSE 'Churned'
	END AS LIFECYCLE_STAGE
	FROM
	CUSTOMER_SUMMARY;

SELECT * FROM RETAIL;

WITH RFM AS (
    SELECT
        CUSTOMER_ID,
		COUNTRY,
        CURRENT_DATE - MAX(ORDER_DATE) AS RECENCY,
        COUNT(TRANSACTION_ID) AS FREQUENCY,
        SUM(TOTAL_AMOUNT) AS MONETARY
    FROM RETAIL
    GROUP BY CUSTOMER_ID,COUNTRY
),
SCORES AS (-- relative ranking of customers
    SELECT
        CUSTOMER_ID,
		COUNTRY,
        NTILE(5) OVER (ORDER BY RECENCY ASC)    AS R_SCORE,
        NTILE(5) OVER (ORDER BY FREQUENCY DESC) AS F_SCORE,
        NTILE(5) OVER (ORDER BY MONETARY DESC)  AS M_SCORE
    FROM RFM
)
SELECT -- segmentation
    CUSTOMER_ID,
	COUNTRY,
    R_SCORE ,
    F_SCORE,
    M_SCORE,
    CONCAT(R_SCORE ,F_SCORE,M_SCORE) AS RFM_CODE,
    CASE
        WHEN R_SCORE >= 4 AND F_SCORE >= 4 AND M_SCORE >= 4 THEN 'CHAMPIONS'
        WHEN R_SCORE >= 3 AND F_SCORE >= 3 AND M_SCORE >= 3 THEN 'LOYAL CUSTOMERS'
        WHEN R_SCORE >= 4 AND F_SCORE <= 2 THEN 'NEW CUSTOMERS'
        WHEN R_SCORE <= 2 AND F_SCORE >= 3 THEN 'AT RISK'
        WHEN R_SCORE  = 1 AND F_SCORE = 1 THEN 'LOST CUSTOMERS'
        ELSE 'POTENTIAL'
    END AS CUSTOMER_SEGMENT
FROM SCORES;

-- PYTHON RFM FILE EXPORT
SELECT *
FROM rfm_analysis
LIMIT 10;



